# Generated by Django 4.2.1 on 2023-06-04 11:58

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('auction_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='static/item_default.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1024, 1024], upload_to=''),
        ),
    ]
