# Generated by Django 4.2.1 on 2023-05-07 10:39

import auction_website.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20, validators=[auction_website.validators.validate_password])),
            ],
        ),
    ]
