# Generated by Django 4.2.1 on 2023-05-17 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction_website', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to='auction_website.itemphoto'),
        ),
        migrations.AddField(
            model_name='item',
            name='user_seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
