# Generated by Django 4.2.1 on 2023-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_website', '0003_item_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='nickname',
            new_name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
