# Generated by Django 4.2.1 on 2023-05-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_website', '0006_account_is_active_account_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
    ]
